version: '3.9'

services:
  web:
    build: .
    command: sh -c "cd dqr && gunicorn dqr.wsgi -w 3 --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./db:/db
      - ./static:/static
      - ./media:/media