# Generated by Django 4.2.2 on 2023-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_internalurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalUrl',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='url',
            new_name='external_url',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='internal_url',
            field=models.CharField(default='google.it', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
