# Generated by Django 4.2.2 on 2023-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_alter_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
